stages:
  - prepare
  - release

generate_version:
  stage: prepare
  rules:
    - if: '$SCHEDULE_TYPE == "release"'
  script:
    - chmod +x generate_version.sh  # Set executable permissions
    - source ./generate_version.sh      # Call the script
    - echo "Release will be version - ${VERSION}"
    - echo "VERSION=${VERSION}" >> build.env
  artifacts:
    reports:
      dotenv: build.env 
  

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$SCHEDULE_TYPE == "release"'
  needs: ["generate_version"]  
  script:
    - echo "$VERSION"  # Output is: 'value_from_generate_version'
    - echo "running release_job for BGS Vocablaries ${VERSION}"  
  release:  
    tag_name: ${VERSION}
    name: 'BGS Vocablaries ${VERSION}'
    description: 'Snapshot of BGS Vocablaries on ${VERSION}.15.'
