stages:
  - prepare
  - release

generate_version:
  stage: prepare
  only:
    - main
  script:
    - chmod +x generate_version.sh  # Set executable permissions
    - source ./generate_version.sh      # Call the script
    - echo "Release will be version - ${VERSION}"
    - echo ${VERSION} > version.txt
  artifacts: 
   paths: 
      - version.txt  
  

release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  # rules:
  #   - if: '$SCHEDULE_TYPE == "release"'
  script:
    - VERSION=$(cat version.txt)
    - echo "running release_job for BGS Vocablaries ${VERSION}"  
  release:
    tag_name: $VERSION
    name: 'BGS Vocablaries $VERSION'
    description: 'Snapshot of BGS Vocablaries on ${VERSION}.15.'
