stages:
  - prepare
  - release

generate_version:
  stage: prepare
  script:
    - chmod +x generate_version.sh  # Set executable permissions
    - generate_version.sh        # Call the script
    - echo "Release will be version - ${VERSION}"
  only:
    - main

release:
  # Caution, as of 2021-02-02 these assets links require a login, see:
  # https://gitlab.com/gitlab-org/gitlab/-/issues/299384
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$SCHEDULE_TYPE == "release"'
  script:
    - echo "running release_job for $TAG"  
  release:
    tag_name: $VERSION
    name: 'BGS Vocablaries $VERSION'
    description: 'Release created using the release-cli.'
